### Numpy 배열 생성하기 - array(), rand()

In [ ]:
'''
Numpy는 Numeric Python의 약자이다.
수학분야 관련된 통계작업시 사용하는 파이썬의 가장 기본이되는 라이브러리
과학계산 컴퓨팅 작업과 데이타 분석에 필요한 작업이 가능
리스트와 거의 흡사하지만 
훨씬더 빠르고 메모리 효율성이 높아서 성능상 우위에 있다.

1) import 해서 쓴다.
2) array() 사용
3) random의 랜덤함수들 사용
'''

##### np배열과 리스트를 각각 생성, 비교

In [1]:
import numpy as np

In [8]:
#1. array() 사용해서 np배열을 생성
'''
1. 리스트는 출력결과가 [ ] 안에...요소들이 , 로 구분
2. np배열은 출력결과가 [ ] 안에...요소들이 , 로 구분되지 않는다.
3. np배열은 ndarray객체 타입으로 나온다.
   ndarray객체는 다차원 행렬구조를 지원하는 Numpy의 핵심클래스이다.
   
'''
myList = [4,5,6,7]
print(myList)

myArr = np.array(myList)
print(myArr)

print(type(myList))
print(type(myArr)) #numpy.ndarray : 다차원 배열이라는 뜻

[4, 5, 6, 7]
[4 5 6 7]
<class 'list'>
<class 'numpy.ndarray'>


In [15]:
myList
myArr

myL_sub = myList[1:3]
print(myL_sub)

myA_sub = myArr[1:3]
print(myA_sub)

myL_sub[0] = -5
print(myL_sub)

myA_sub[0] = -5
print(myA_sub)

print(myList)
print(myArr)

[5, 6]
[-5  6]
[-5, 6]
[-5  6]
[4, 5, 6, 7]
[ 4 -5  6  7]


In [42]:
# 2. 랜덤함수 사용해서 생성..
# rand(), randint()

a = np.random.rand(5)
print(a)
print(type(a))

b = np.random.randint(0,2,100)
print(b)
print(type(b))

c = np.random.randn(10) #가우시안 표준분포
print(c)
print(type(c))

[0.77921918 0.78003936 0.50812736 0.24334464 0.19904041]
<class 'numpy.ndarray'>
[1 0 1 0 1 1 1 0 0 0 1 1 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 1 0 1 1 1 0 1 1 0
 0 0 1 1 1 0 1 0 0 0 1 1 0 1 1 1 1 0 1 1 1 0 1 1 1 1 0 1 1 0 1 1 0 1 1 0 0
 0 0 1 0 1 1 0 1 1 1 0 1 1 0 0 1 0 0 0 1 1 1 0 1 1 1]
<class 'numpy.ndarray'>
[ 0.35437028 -1.16592251  0.63778651 -1.21369796 -1.25703764 -1.47449986
 -1.03474208  0.45531349 -0.58708194  0.20377692]
<class 'numpy.ndarray'>


In [47]:
## 리스트와의 차이점
'''
np배열은 하나의 자료형만 저장 가능
즉, 숫자와 문자를 동시에 저장할수 없다.
만약에 숫자와 문자가 동시에 저장되어지면 더큰 데이타타입은 문자로 변환되어 저장
이러한 제약을 가지는 이유....내부 원소에 대한 접근과 반복문 실행을 빨리하기 위함
나중에 배우게될 Series에서 다시 한번 언급...!!!

값을 타입을 명시할수도 있다.
dtype 속성을 사용한다..int32, int64, float32, float64
'''
L = [1, 2, 3, '4', 5, 6, 7]
L

narr1 = np.array([1,2,'3','4',5,6])
narr1

narr2 = np.array([1, 2, 3, 4.0, 5, 6])
narr2

narr3 = np.array([1.0, 2.0, 3.0, 4.0, 5.0], dtype='int32') # flooat64
narr3

array([1, 2, 3, 4, 5])

### 배열 초기화

In [41]:
# 1. 0값으로 초기화...zeros()
az = np.zeros(10)
print(az)

# 2. 1값으로 초기화...ones()
ao = np.ones(10)
print(ao)

# 3. 3 으로 초기화....
am = np.zeros(10)+3
print(am)

# 4. 
ae = np.eye(5) # 3x3
print(ae)

# 5. arange()
print(np.arange(3))
print(np.arange(0,3))
print(np.arange(3,10,2))

# 6. full()
af = np.full?
af = np.full((5,5), -11, dtype='int32')
print(af)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[0 1 2]
[0 1 2]
[3 5 7 9]
[[-11 -11 -11 -11 -11]
 [-11 -11 -11 -11 -11]
 [-11 -11 -11 -11 -11]
 [-11 -11 -11 -11 -11]
 [-11 -11 -11 -11 -11]]


### Numpy 배열의 속성과 기본함수
#### ndim, shape, reshape, size, dtype, type

In [57]:
# arr1 = np.array([[1.0, 2, 3], [4, 5, 6]], dtype='int32')
arr1 = np.array([[1.0, 2, 3], [4, 5, 6]], dtype=np.int32)
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
print(type(arr1))
print(np.ndim(arr1)) # ndim은 함수
print(np.shape(arr1))
print(np.size(arr1))

print('*'*30)
#arr1 배열의 요소값 타입을 한번에 바꿀때 사용
arr1_1 = arr1.astype(np.float64) #astype() == dtype...요소에 해당하는것들
print(arr1_1)
print(type(arr1_1))# 객체 자체의 타입을 리턴

print('*'*30)
arr2 = np.arange(32).reshape(4,8)
arr2

<class 'numpy.ndarray'>
2
(2, 3)
6
******************************
[[1. 2. 3.]
 [4. 5. 6.]]
<class 'numpy.ndarray'>
******************************


array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

### 랜덤함수와 seed값 설정하기

In [ ]:
'''
Numpy의 random 모듈(서브패키지)에는 난수를 생성하는 다양한 함수들이 존재
그중에서 가장 많이 사용되는 3가지를 정리....

rand : 0~1사이의 실수값을 반환 - rand(행, 열)
randn : 가우시안 정규분포값 randn(행, 열)
randint : randint(row, high, size)
'''

In [68]:
arr3 = np.random.randn(4,4) # 내부적으로 컴퓨터 시각으로 측정
arr3

array([[-0.6964783 , -0.26241234,  1.62459924,  0.87967666],
       [ 1.73064458, -0.78587357, -0.75202078, -1.63603162],
       [-0.63157719, -2.59792762, -0.86435373, -1.628227  ],
       [-0.04533108, -0.32768598, -0.57434587,  0.06188592]])

In [75]:
# seed값 설정하기
# 특정한 시작 숫자를 제공해서 난수를 발생...고정적인 난수가 발생
# 실행할때마다 난수값이 바뀌지 않기때문에 분석결과를 확인하는데 용이
# seed값은 한번만 정해주면 계속 유지된다...

np.random.seed(404)
arr3 = np.random.randn(4,4)
arr3

array([[-1.18269089,  1.33746165, -0.31430504,  0.5566431 ],
       [-0.20929933, -0.01180037,  1.23493345, -0.04341894],
       [-0.68178724,  1.20069197,  1.34394438, -0.834109  ],
       [ 1.0359977 ,  1.6657991 ,  0.94947856,  1.06700952]])