### 인덱싱, 슬라이싱

In [2]:
import numpy as np

In [3]:
narray = np.arange(5)
narray

array([0, 1, 2, 3, 4])

In [11]:
print(narray[1], narray[-1]) # 음수가 붙으면 뒤에서 n번째로 이해
print(narray[1:])
print(narray[1:5])
print(narray[:])
print(narray[2:4]) # 두번째 인덱스는 포함하지 않는다.

1 4
[1 2 3 4]
[1 2 3 4]
[0 1 2 3 4]
[2 3]


In [12]:
narray1 = np.random.randint?

In [ ]:
'''
2차원 배열에서의 인덱싱, 슬라이싱
인덱스는 [ , ] 콤마를 기준으로 2개의 인자를 받는다.
앞 인자값은 행의 index, 뒤 인자값은 열의 index

, 없이 : 를 넣으면 모든것을 다 포함한다.
'''

In [16]:
np.random.seed(100)
narray1 = np.random.randint(0, 20, 16).reshape(4,4)
narray1

array([[ 8,  3,  7, 15],
       [16, 10,  2,  2],
       [ 2, 14,  2, 17],
       [16, 15,  4, 11]])

In [27]:
#1. narray1 에서 첫번째줄 7을 가져오려면
narray1[0, 2]
narray1[0][2]

#2. 두번째 라인 [16, 10, 2, 2]을 가져오려면
narray1[1, 0:4]
narray1[1, 0:]
narray1[1, :]
narray1[1:2, :] # 2차원출력

# 3. 전체행에 대해서 4번째 열만 다 가져오려면
narray1[0:4, 3:4]
narray1[:, 3:]
narray1[:, 3] # 차원이 줄어든다.

# 4. 전체행에 대해서 1,2번째 열만 다 가져오려면
narray1[:, :2]

array([[ 8,  3],
       [16, 10],
       [ 2, 14],
       [16, 15]])

### 인덱싱과 조건 슬라이싱

In [29]:
np.random.seed(0)
arr3 = np.random.randn(4,4)
arr3

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433]])

In [33]:
# 1. 논리연산자 사용
arr3[arr3>0]
arr3[arr3<0]

# 2. 0 보다 작은값들을 전부 0으로 바꿔보겠다.
arr3[arr3<0] = 0
arr3 # 원본도 같이 바뀐다.

array([[1.76405235, 0.40015721, 0.97873798, 2.2408932 ],
       [1.86755799, 0.        , 0.95008842, 0.        ],
       [0.        , 0.4105985 , 0.14404357, 1.45427351],
       [0.76103773, 0.12167502, 0.44386323, 0.33367433]])

In [37]:
# 3. where 함수
'''
arr3가 0보다 크면 arr3를 그대로 리턴
arr3가 0보다 작으면 -1을 리턴....
'''

arr3_1 = np.where(arr3!=0, arr3, -1) # !!!
arr3_1

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -1.        ,  0.95008842, -1.        ],
       [-1.        ,  0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433]])

In [46]:
a = np.array([[1,2], [3,4], [5,6]])
bool_a = (a>2)
print(bool_a)

print(a[bool_a])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]


### Numpy 통계함수

In [47]:
arr4 = np.random.randint(0, 20, 16).reshape(4,4)
arr4

array([[18,  3, 17, 19],
       [19, 19, 14,  7],
       [ 0,  1,  9,  0],
       [10,  3, 11, 18]])

In [55]:
'''
numpy 배열의 통계함수
sum(), mean(), min(), max(), argmin(), argmax(), cumsum()
'''

print(np.sum(arr4))
print(np.sum(arr4, axis=1)) #axis=0이 행.. 열끼리 합함, 1이면 행끼리 합함.. 헷갈려!!.. 키워드 매개변수라 기본값이 None
print(np.sum(arr4, axis=0)) #axis=0 이 행기준으로 ,sum
print(np.cumsum(arr4, axis=0)) #누적합
'''
axis=0
모든 행들을 다 검색
그중에서 가장 큰값의 인덱스를 리턴하도록
'''
print(np.argmax(arr4, axis=0))

168
[57 59 10 42]
[47 26 51 44]
[[18  3 17 19]
 [37 22 31 26]
 [37 23 40 26]
 [47 26 51 44]]
[1 1 0 0]
