### Pytorch 에서의 Gradient Descent
    우리는 이전 머신러닝 과정에서 선형회귀(Linear Regression)에 대해서 간단히 살펴보았다.
    이번에는 파이토치를 이용해서 선형회귀를 위한 연산 그래프를 만들고 경사하강법을 이해하는 코드
    를 다시 작성해 봅니다. 파이토치에서는 데이타의 기본단위 텐서(Tensor)를 사용합니다.
    Numpy에서 np.array([1,2,3]) 와 동일한 겁니다.
    이러한 텐서를 연산의 기본단위로 사용합니다. 텐서를 생성하는 방법에는 torch.tensor()...

In [1]:
import torch # 그냥 torch로 부른다.
import torchvision # 파이토치에서 vision은 Image Processing에 특화된 라이브러리
import torch.nn as nn # nn 은 Neural Net
import numpy as np
import torchvision.transforms as transforms # transforms...data augmentation

In [6]:
X = torch.Tensor(2,3)
X
X.shape
X.size()

X = torch.Tensor([[1, 2, 3], [4, 5, 6]])
X

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [20]:
'''
tensor()함수 인자값으로 data.dtype, device, requires_grad 등이 있다.
dtype - 타입지정
device - 텐서를 어느 기기에 올릴것인가를 지정...(cpu, gpu)
requires_grad - 텐서에 기울기를 지정할지를 여부..(False)...미분사용 여부
'''

x = torch.tensor(data=[2.0, 3.0], requires_grad=True)
# x = torch.tensor(data=[2.0, 3.0])
x

y = x**2
y

# 1. 예측값 출력
pred = 2*y + 3 # 2x^ + 3
pred

target = torch.tensor([3.0, 4.0])

# 2. loss 값을 구한다.
loss = torch.sum(torch.abs(pred-target)) # (11-3) + (21-4) = 25
loss
print('loss ', loss)

# 3. 가장 가파른 기울기로 하강하는 weight를 찾는다.
# 가장 낮은 loss값을 구하는 weight를 찾는다....미분, 편미분...backpropagation

loss.backward()

'''
x.grad ---> dy/dw = x
w.grad ---> dy/dx = w
'''
print(x.grad, pred.grad)

loss  tensor(25., grad_fn=<SumBackward0>)
tensor([ 8., 12.]) None


### Tensor Type - tensor(), as_tensor()
    Numpy 배열을 torch.Tensor 변형

In [28]:
'''
Pytorch의 텐서 자료형은 Numpy의 array()와 동일한 것으로 이해...

'''
# 1.
li = np.array([[1, 2], [3, 4]])
print(li)
print(li.dtype)
print(type(li))

print('*' * 40)

li_torch = torch.tensor(li)
print(li_torch)
print(type(li_torch))

print('*' * 40)

li_as_torch = torch.as_tensor(li)
print(li_as_torch)
print(type(li_as_torch))

print('*' * 40)
# 반대로 텐서를 Numpy 배열로 변형....torch.numpy()
li_tensor_numpy = li_as_torch.numpy()
print(type(li_tensor_numpy))

[[1 2]
 [3 4]]
int32
<class 'numpy.ndarray'>
****************************************
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
<class 'torch.Tensor'>
****************************************
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
<class 'torch.Tensor'>
****************************************
<class 'numpy.ndarray'>
