In [1]:
import keras
from keras import models, layers
import numpy as np

In [2]:
# 1. Data Generator
x = np.array([0,1,2,3,4])
y = 2 * x +1

print(x)
print(y)

[0 1 2 3 4]
[1 3 5 7 9]


In [3]:
# 2. Model Generator
'''
units - 히든레이어의 유닛의 갯수
**kwargs : 이런건 없다...input_shape=(1,)
'''
model=models.Sequential()
model.add(layers.Dense(1,input_shape=(1,)))
# layers.Dense?

In [4]:
# 3. ...opmizer에 해당하는 부분,,loss에 해당하는 부분...compile
model.compile(optimizer=keras.optimizers.SGD(0.01), loss='mse', metrics=['accuracy'])

In [5]:
# 4. 학습을 진행
model.fit(x[:4], y[:4], epochs = 100, verbose=0)
print(x[:4])
print(y[:4])

[0 1 2 3]
[1 3 5 7]


In [6]:
# 5. 예측
print('Y Value : ', y[3:])
print('Prediction : ', model.predict(x[3:]).flatten()) # 1차원으로 펼쳐서

Y Value :  [7 9]
Prediction :  [7.085401 9.184743]


In [7]:
# 6. Evaluate
loss_function=model.evaluate(x[3:], y[3:])
print(loss_function)

1/1 [==============================] - 0s 0s/step - loss: 0.0207 - accuracy: 0.0000e+00
[0.020711643621325493, 0.0]


In [8]:
eval_model=model.evaluate(x[3:], y[3:])
print('Loss:{}, Accuracy:{}'.format(*eval_model))

1/1 [==============================] - 0s 1ms/step - loss: 0.0207 - accuracy: 0.0000e+00
Loss:0.020711643621325493, Accuracy:0.0
